// <auto-generated />
using LogicoStartupEngine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LogicoStartupEngine.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    partial class ApplicationDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LogicoStartupEngine.Models.LogisticCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("CompanyDescription")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("CompanyImageURL")
                        .IsRequired()
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("CompanyLocation")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CompanyPhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(13)");

                    b.Property<string>("CompanyReferenceEmail")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("CompanyReferencePhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(13)");

                    b.Property<string>("CompanyRegistrationNumber")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CompanyTaxRegistrationNumber")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("CompanyWebsiteURL")
                        .IsRequired()
                        .HasColumnType("varchar(2048)");

                    b.HasKey("Id");

                    b.ToTable("LogisticCompanies");
                });
#pragma warning restore 612, 618
        }
    }
}
